heroku_dev: &heroku_dev
  host: ec2-54-247-79-142.eu-west-1.compute.amazonaws.com
  adapter: postgresql
  database: dcrc47jt3asttp
  username: clalmadevtfngq
  password: 8gJqLeyXLY-COJMU9zWnl1ORv0

local: &local
  host: localhost
  adapter: postgresql
  database: pvpc
  username: pvpc
  password: pvpc123

development:
  <<: *heroku_dev

staging:
  <<: *heroku_dev

test:
  <<: *local

production:
  <<: *heroku_dev

vagrant:
  adapter: postgresql
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  username: postgres
