local: &local
  adapter: postgresql
  host: localhost
  port: 5432
  database: core
  username: core
  password: core

docker: &docker
  adapter: postgresql
  host: <%= ENV['POSTGRES_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['POSTGRES_PORT_5432_TCP_PORT'] %>
  username: postgres

development:
  <<: *local

test:
  <<: *local

vagrant:
  <<: *docker
