local: &local
  username: 'rabbitmq'
  password: 'rabbitmq'

docker: &docker
  host: <%= ENV['RABBITMQ_PORT_5672_TCP_ADDR'] %>
  port: <%= ENV['RABBITMQ_PORT_5672_TCP_PORT'] %>
  username: 'rabbitmq'
  password: 'rabbitmq'

development:
  <<: *local

test:
  <<: *local

vagrant:
  <<: *docker
