---
- hosts: vm
  tasks:
    - lineinfile: dest=/etc/environment insertafter=EOF line={{ item }}
      sudo: yes
      with_items:
        - LC_ALL=\"en_US.utf-8\"
        - LANGUAGE=\"en_US.utf-8\"
    - command: shutdown -r now
      sudo: yes
    - local_action: wait_for host={{ inventory_hostname }} port=22
    - apt: name=postgresql
      sudo: yes
    - apt: update_cache=yes
      sudo: yes
    - apt: name={{ item }}
      sudo: yes
      with_items:
        - python-pip
        - postgresql-server-dev-all
        - python-dev
        - redis-server
        - rabbitmq-server
    - pip: name=psycopg2
      sudo: yes
    - postgresql_db: name=pvpc
      sudo: yes
      sudo_user: postgres
    - postgresql_user: name=pvpc password=pvpc123
      sudo: yes
      sudo_user: postgres
